#!/usr/bin/python

DOMAIN = "puresources"
PATH = "/usr/share/pureos/locale"

import os, gettext, sys
sys.path.append('/usr/lib/pureos/common')
import additionalfiles

os.environ['LANG'] = "en_US.UTF-8"
gettext.install(DOMAIN, PATH)

prefix = "[Desktop Entry]\n"

suffix = """Exec=software-sources
Icon=software-sources
Terminal=false
X-MultipleArgs=false
Type=Application
Categories=GNOME;GTK;System;Settings;X-GNOME-SystemSettings;X-GNOME-Settings-Panel;XFCE;X-XFCE-SettingsDialog;X-XFCE-SystemSettings;
X-GNOME-Settings-Panel=software-properties
MimeType=text/x-apt-sources-list;
X-KDE-SubstituteUID=true
NotShowIn=KDE;
"""

additionalfiles.generate(DOMAIN, PATH, "usr/share/applications/puresources.desktop", prefix, _("Software Sources"), _("Configure the sources for installable software and updates"), suffix)