# Trisquel User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.datareporting-healthreport-lastDailyCollection", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "US");
user_pref("browser.search.region", "US");
user_pref("browser.search.useDBForOrder", true);
user_pref("browser.syncPromoViewsLeftMap", "{\"bookmarks\":4}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"https-everywhere-button\",\"widget:torproxy@trisquel-private-browsing-proxy\",\"widget:jid1-AVgCeF1zoVzMjA@jetpack-agent-spoof\",\"toggle-button--jid1-mnnxcxisbpnsxqjetpack-pb-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"toggle-button--jid1-mnnxcxisbpnsxqjetpack-pb-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.currentDaySubmissionFailureCount", 1);
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1438210923936");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1438211823946");
user_pref("datareporting.healthreport.pendingDeleteRemoteData", true);
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1438210923661");
user_pref("distribution.trisquel.bookmarksProcessed", true);
user_pref("extensions.agentSpoof.acceptDefault", false);
user_pref("extensions.agentSpoof.acceptEncoding", false);
user_pref("extensions.agentSpoof.acceptLang", false);
user_pref("extensions.agentSpoof.browsingHistory", false);
user_pref("extensions.agentSpoof.cache", false);
user_pref("extensions.agentSpoof.dns", false);
user_pref("extensions.agentSpoof.dom", false);
user_pref("extensions.agentSpoof.enabled", true);
user_pref("extensions.agentSpoof.excludeList", "abU,abV");
user_pref("extensions.agentSpoof.fonts", false);
user_pref("extensions.agentSpoof.geo", false);
user_pref("extensions.agentSpoof.ifnone", false);
user_pref("extensions.agentSpoof.link", false);
user_pref("extensions.agentSpoof.notify", true);
user_pref("extensions.agentSpoof.randomDesktopCount", 2);
user_pref("extensions.agentSpoof.randomOtherCount", 0);
user_pref("extensions.agentSpoof.screenSize", "default");
user_pref("extensions.agentSpoof.tabHistory", false);
user_pref("extensions.agentSpoof.timeInterval", "none");
user_pref("extensions.agentSpoof.totalRandomAllCount", 373);
user_pref("extensions.agentSpoof.totalRandomDesktopCount", 228);
user_pref("extensions.agentSpoof.tzOffset", "default");
user_pref("extensions.agentSpoof.uaChosen", "default");
user_pref("extensions.agentSpoof.via", false);
user_pref("extensions.agentSpoof.viadd", "random");
user_pref("extensions.agentSpoof.viaip", "1.1.1.1");
user_pref("extensions.agentSpoof.webGl", false);
user_pref("extensions.agentSpoof.xff", false);
user_pref("extensions.agentSpoof.xffdd", "random");
user_pref("extensions.agentSpoof.xffip", "1.1.1.1");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"torproxy@trisquel\":{\"version\":\"2.3\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/torproxy@trisquel\",\"multiprocessCompatible\":false},\"html5-video-everywhere@lejenome.me\":{\"version\":\"0.2.38.1-signed\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/html5-video-everywhere@lejenome.me\",\"multiprocessCompatible\":false},\"jid1-AVgCeF1zoVzMjA@jetpack\":{\"version\":\"0.9.3.1.1-signed\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/jid1-AVgCeF1zoVzMjA@jetpack\",\"multiprocessCompatible\":false},\"jid1-MnnxcxisBPnSXQ@jetpack\":{\"version\":\"0.2.6\",\"type\":\"extension\",\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/jid1-MnnxcxisBPnSXQ@jetpack\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "aboutabrowser%40trisquel.info:1.0,https-everywhere%40eff.org:5.0.6,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:38.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.https_everywhere.firstrun_context_menu", false);
user_pref("extensions.https_everywhere.prefs_version", 1);
user_pref("extensions.https_everywhere.toolbar_hint_shown", true);
user_pref("extensions.jid1-MnnxcxisBPnSXQ@jetpack.doNotTrackDefaultEnabled", true);
user_pref("extensions.lastAppVersion", "38.0");
user_pref("extensions.lastPlatformVersion", "38.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.sdk-widget-inserted.widget:jid1-AVgCeF1zoVzMjA@jetpack-agent-spoof", true);
user_pref("extensions.sdk-widget-inserted.widget:torproxy@trisquel-private-browsing-proxy", true);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-en-ZA@abrowser.mozilla.org\":{\"d\":\"/usr/lib/abrowser/browser/extensions/langpack-en-ZA@abrowser.mozilla.org.xpi\",\"e\":false,\"v\":\"39.0\",\"st\":1437066673000},\"aboutabrowser@trisquel.info\":{\"d\":\"/usr/lib/abrowser/browser/extensions/aboutabrowser@trisquel.info\",\"e\":true,\"v\":\"1.0\",\"st\":1437421493000,\"mt\":1435293836000},\"langpack-en-GB@abrowser.mozilla.org\":{\"d\":\"/usr/lib/abrowser/browser/extensions/langpack-en-GB@abrowser.mozilla.org.xpi\",\"e\":false,\"v\":\"39.0\",\"st\":1437066673000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/abrowser/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"38.0\",\"st\":1437421493000,\"mt\":1435359764000}},\"app-system-share\":{\"torproxy@trisquel\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/torproxy@trisquel\",\"e\":true,\"v\":\"2.3\",\"st\":1437415507000,\"mt\":1404958844000},\"html5-video-everywhere@lejenome.me\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/html5-video-everywhere@lejenome.me\",\"e\":true,\"v\":\"0.2.38.1-signed\",\"st\":1437416978000,\"mt\":1432261266000},\"jid1-AVgCeF1zoVzMjA@jetpack\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/jid1-AVgCeF1zoVzMjA@jetpack\",\"e\":true,\"v\":\"0.9.3.1.1-signed\",\"st\":1437415506000,\"mt\":1403718956000},\"jid1-MnnxcxisBPnSXQ@jetpack\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/jid1-MnnxcxisBPnSXQ@jetpack\",\"e\":true,\"v\":\"0.2.6\",\"st\":1437415505000,\"mt\":1427927256000},\"https-everywhere@eff.org\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/https-everywhere@eff.org\",\"e\":true,\"v\":\"5.0.6\",\"st\":1437415504000,\"mt\":315561600000}}}");
user_pref("gecko.buildID", "20150626224248");
user_pref("gecko.mstone", "38.0");
user_pref("media.gmp-manager.buildID", "20150626224248");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.proxy.socks", "127.0.0.1");
user_pref("network.proxy.socks_port", 9050);
user_pref("network.proxy.socks_remote_dns", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1438210923);
user_pref("toolkit.telemetry.previousBuildID", "20150626224248");
