#!/bin/sh

item="/etc/gtk-3.0/settings.ini"

[ -f "$item"".ubuntu" ] && exit 0 || true

dpkg-divert --package pureos-desktop-common-data --add --rename --divert "$item"".ubuntu" "$item"

cat << EOF > $item
[Settings]
gtk-theme-name = PureOS
gtk-icon-theme-name = pureos
gtk-fallback-icon-theme = gnome
gtk-sound-theme-name = freedesktop
gtk-icon-sizes = panel-menu-bar=24,24
EOF


