#!/bin/sh

item="/etc/gtk-3.0/settings.ini"

if [ remove = "$1" -o abort-install = "$1" -o disappear = "$1" -o abort-upgrade = "$1" ]
then
    [ -f "$item"".pureos" ] && dpkg-divert --package pureos-desktop-common-data --remove --rename --divert "$item"".pureos" "$item"
fi
